package com.lumah_shop.lumah_shop.pojo;

import com.lumah_shop.lumah_shop.DAO.DAOCategory;
import com.lumah_shop.lumah_shop.DAO.DAOProduct;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;

/**
 * Categories generated by hbm2java
 */
@ManagedBean
public class Categories implements java.io.Serializable {
    private Integer id;
    private String name;
    private String search;
    private String description;
    private List<Categories> categoryList;
    private Set productses = new HashSet(0);
    
    public List<Categories> getAllCategory() {
        DAOCategory cat = new DAOCategory();
        return cat.showAll();
    }
    
    public void store () {
        DAOCategory category = new DAOCategory();
        category.store(this);
    }

    public String getById(int CatId) {
        DAOCategory category = new DAOCategory();
        List<Categories> pro = category.Show(CatId);

        id = pro.get(0).id;
        name = pro.get(0).name;
        description = pro.get(0).description;

        return "category_edit";
    }
    
    public void search() {
        categoryList = search.length() > 0 ? new DAOCategory().ShowByName(search) : this.getAllCategory();
    }
    
    public String update() {
        DAOCategory category = new DAOCategory();
        category.update(this);
        
        return "category";
    }
    
    public void delete(int id) {
        DAOCategory cat = new DAOCategory();
        cat.destroy(id);
    }

    public int categoryTotal () {
        return new DAOCategory().categoryTotal();
    }
    
    public Categories() {
    }

	
    public Categories(String name) {
        this.name = name;
    }
    public Categories(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Categories(String name, String description, Set productses) {
       this.name = name;
       this.description = description;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }

    public List<Categories> getCategoryList() {
        return categoryList == null ? this.getAllCategory() : categoryList;
    }

    public void setCategoryList(List<Categories> categoryList) {
        this.categoryList = categoryList;
    }
    
    public String getSearch() {
        return search;
    }

    public void setSearch(String search) {
        this.search = search;
    }
}


